var currentCategory='restaurants',selectedReels=new Set(),docUrl='',calendarDate=new Date(),selectedShootDate=null,clockStartH=10,clockStartM=0,clockStartAM=true,clockEndH=2,clockEndM=0,clockEndAM=false;
function setCategory(cat){currentCategory=cat;document.querySelectorAll('.vending-btn').forEach(function(b){b.classList.toggle('active',b.dataset.cat===cat);});if(document.getElementById('results').classList.contains('show'))renderResults();}
function initiate(){var btn=document.getElementById('initiateBtn');btn.classList.add('running');btn.disabled=true;selectedReels.clear();updateSelBar();var overlay=document.getElementById('juiceboxOverlay'),juice=document.getElementById('jbJuice'),progress=document.getElementById('jbProgress');overlay.classList.add('active');juice.style.transition='none';juice.style.height='100%';juice.classList.remove('draining');createBubbles();var messages=['Finding the freshest reels','Analyzing engagement rates','Filtering top performers','Ranking by virality','Almost done...'];setTimeout(function(){juice.style.transition='height 6s ease-in-out';juice.classList.add('draining');},200);var msgIdx=0;var msgInterval=setInterval(function(){msgIdx++;if(msgIdx<messages.length)progress.textContent=messages[msgIdx];},1200);setTimeout(function(){clearInterval(msgInterval);overlay.classList.remove('active');juice.classList.remove('draining');btn.classList.remove('running');btn.disabled=false;renderResults();document.getElementById('results').classList.add('show');document.getElementById('results').scrollIntoView({behavior:'smooth'});},6500);}
function createBubbles(){var c=document.getElementById('jbBubbles');c.innerHTML='';for(var i=0;i<12;i++){var b=document.createElement('div');b.className='jb-bubble';b.style.left=Math.random()*90+'%';b.style.bottom=Math.random()*40+'%';b.style.animationDelay=Math.random()*3+'s';b.style.animationDuration=(1+Math.random()*2)+'s';b.style.width=(4+Math.random()*8)+'px';b.style.height=b.style.width;c.appendChild(b);}}
function renderResults(){var data=LOCAL_DATA[currentCategory],grid=document.getElementById('grid'),title=document.getElementById('resultsTitle'),count=document.getElementById('resultsCount');var catNames={restaurants:'Restaurant',hotels:'Hotel',spa:'Spa',b2b:'B2B Tech'};title.textContent='Top '+catNames[currentCategory]+' Reels';count.textContent=data.length+' results';grid.innerHTML=data.map(function(item,i){var ini=item.account.slice(0,2).toUpperCase(),embedUrl=item.reelUrl+'embed/',dlUrl='https://djack-netizen.github.io/personal-bot/dl.html?url='+encodeURIComponent(item.reelUrl),isSel=selectedReels.has(currentCategory+':'+i);return '<div class="card'+(isSel?' selected':'')+'" data-idx="'+i+'"><div class="card-check"><input type="checkbox" '+(isSel?'checked':'')+' onchange="toggleSelect(\''+currentCategory+'\','+i+',this.checked)"></div><div class="card-top"><div class="avatar">'+ini+'</div><span class="username">@'+item.account+'</span></div><iframe class="card-embed" src="'+embedUrl+'" loading="lazy" allowfullscreen allow="encrypted-media"></iframe><div class="card-stats"><div class="card-stat"><div class="stat-val">'+formatNum(item.views)+'</div><div class="stat-label">Views</div></div><div class="card-stat"><div class="stat-val">'+formatNum(item.likes)+'</div><div class="stat-label">Likes</div></div><div class="card-stat"><div class="stat-val">'+formatNum(item.comments)+'</div><div class="stat-label">Comments</div></div><div class="card-stat"><div class="stat-val">'+item.engagement+'%</div><div class="stat-label">Eng.</div></div></div><div class="card-footer"><span class="card-date">'+formatDate(item.date)+'</span><a class="card-dl" href="'+dlUrl+'" target="_blank">\u2B07 Download</a></div></div>';}).join('');}
function toggleSelect(cat,idx,checked){var key=cat+':'+idx;if(checked)selectedReels.add(key);else selectedReels.delete(key);document.querySelectorAll('.card').forEach(function(c){var ci=parseInt(c.dataset.idx);c.classList.toggle('selected',selectedReels.has(currentCategory+':'+ci));});updateSelBar();}
function clearSelection(){selectedReels.clear();document.querySelectorAll('.card').forEach(function(c){c.classList.remove('selected');});document.querySelectorAll('.card-check input').forEach(function(cb){cb.checked=false;});updateSelBar();}
function updateSelBar(){var bar=document.getElementById('selBar'),count=document.getElementById('selCount'),n=selectedReels.size;bar.classList.toggle('show',n>0);count.textContent=n+' reel'+(n!==1?'s':'')+' selected';}
function buildCalendar(){var wrap=document.getElementById('calendarWrap'),today=new Date(),year=calendarDate.getFullYear(),month=calendarDate.getMonth(),firstDay=new Date(year,month,1).getDay(),daysInMonth=new Date(year,month+1,0).getDate(),daysInPrev=new Date(year,month,0).getDate(),months=['January','February','March','April','May','June','July','August','September','October','November','December'];var html='<div class="calendar-nav"><button onclick="navCalendar(-1)">&lt;</button><span class="calendar-month">'+months[month]+' '+year+'</span><button onclick="navCalendar(1)">&gt;</button></div><div class="calendar-grid">';var dows=['Su','Mo','Tu','We','Th','Fr','Sa'];dows.forEach(function(d){html+='<div class="calendar-dow">'+d+'</div>';});for(var i=firstDay-1;i>=0;i--)html+='<div class="calendar-day other-month">'+(daysInPrev-i)+'</div>';for(var d=1;d<=daysInMonth;d++){var cls='calendar-day';if(d===today.getDate()&&month===today.getMonth()&&year===today.getFullYear())cls+=' today';if(selectedShootDate&&d===selectedShootDate.getDate()&&month===selectedShootDate.getMonth()&&year===selectedShootDate.getFullYear())cls+=' selected';html+='<div class="'+cls+'" onclick="selectCalDay('+d+')">'+ d+'</div>';}var totalCells=firstDay+daysInMonth,remaining=(7-totalCells%7)%7;for(var i=1;i<=remaining;i++)html+='<div class="calendar-day other-month">'+i+'</div>';html+='</div>';wrap.innerHTML=html;}
function navCalendar(dir){calendarDate.setMonth(calendarDate.getMonth()+dir);buildCalendar();}
function selectCalDay(day){selectedShootDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),day);buildCalendar();}
function buildClock(id,h,m,ampm){var wrap=document.getElementById(id),hStr=(h<10?'0':'')+h,mStr=(m<10?'0':'')+m;wrap.innerHTML='<div class="clock-segment"><button onclick="adjClock(\''+id+'\',\'h\',1)">&#9650;</button><div class="clock-digit">'+hStr+'</div><button onclick="adjClock(\''+id+'\',\'h\',-1)">&#9660;</button></div><div class="clock-colon">:</div><div class="clock-segment"><button onclick="adjClock(\''+id+'\',\'m\',1)">&#9650;</button><div class="clock-digit">'+mStr+'</div><button onclick="adjClock(\''+id+'\',\'m\',-1)">&#9660;</button></div><div class="clock-ampm" onclick="adjClock(\''+id+'\',\'ap\',0)">'+(ampm?'AM':'PM')+'</div>';}
function adjClock(id,type,dir){if(id==='clockStart'){if(type==='h')clockStartH=((clockStartH-1+dir+12)%12)+1;else if(type==='m')clockStartM=(clockStartM+dir*15+60)%60;else clockStartAM=!clockStartAM;buildClock('clockStart',clockStartH,clockStartM,clockStartAM);}else{if(type==='h')clockEndH=((clockEndH-1+dir+12)%12)+1;else if(type==='m')clockEndM=(clockEndM+dir*15+60)%60;else clockEndAM=!clockEndAM;buildClock('clockEnd',clockEndH,clockEndM,clockEndAM);}}
function openPlanModal(){document.getElementById('planModal').classList.add('active');document.getElementById('planForm').style.display='block';document.getElementById('planLoading').style.display='none';document.getElementById('planResult').style.display='none';buildCalendar();buildClock('clockStart',clockStartH,clockStartM,clockStartAM);buildClock('clockEnd',clockEndH,clockEndM,clockEndAM);}
function closePlanModal(){document.getElementById('planModal').classList.remove('active');}
function generateShotList(){var client=document.getElementById('clientSelect').value;if(!client){alert('Please select a client');return;}if(!selectedShootDate){alert('Please select a shoot date');return;}var shootDate=selectedShootDate.toISOString().slice(0,10),shootStart=(clockStartH<10?'0':'')+clockStartH+':'+(clockStartM<10?'0':'')+clockStartM+' '+(clockStartAM?'AM':'PM'),shootEnd=(clockEndH<10?'0':'')+clockEndH+':'+(clockEndM<10?'0':'')+clockEndM+' '+(clockEndAM?'AM':'PM'),shotTypes=[].slice.call(document.querySelectorAll('.checkbox-group input:checked')).map(function(cb){return cb.value;});var reels=[];selectedReels.forEach(function(key){var parts=key.split(':');reels.push(LOCAL_DATA[parts[0]][parseInt(parts[1])]);});document.getElementById('planForm').style.display='none';document.getElementById('planLoading').style.display='block';var payload={client:client,shootDate:shootDate,shootStart:shootStart,shootEnd:shootEnd,shotTypes:shotTypes,reels:reels};fetch('https://script.google.com/a/macros/openventures.io/s/PLACEHOLDER/exec',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json();}).then(function(data){docUrl=data.docUrl||'https://docs.google.com/document/d/PLACEHOLDER';showShotResult();}).catch(function(){docUrl='https://docs.google.com/document/d/PLACEHOLDER';setTimeout(showShotResult,2000);});}
function showShotResult(){document.getElementById('planLoading').style.display='none';document.getElementById('planResult').style.display='block';document.getElementById('docLink').href=docUrl;}
function copyDocLink(){navigator.clipboard.writeText(docUrl).then(function(){var btn=event.target;btn.textContent='Copied!';setTimeout(function(){btn.textContent='Copy Link';},2000);});}
function emailDoc(){var subject=encodeURIComponent('Shot List - OPN Agency'),body=encodeURIComponent('Here is the shot list: '+docUrl);window.open('mailto:?subject='+subject+'&body='+body);}
document.getElementById('planModal').addEventListener('click',function(e){if(e.target===document.getElementById('planModal'))closePlanModal();});
function formatNum(n){if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toString();}
function formatDate(d){var dt=new Date(d+'T00:00:00');return dt.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
