var LOCAL_DATA={restaurants:[{account:'theinfatuation',reelUrl:'https://www.instagram.com/reel/C8xN6zHODJk/',views:1200000,likes:45000,comments:890,engagement:3.8,date:'2026-07-15',caption:'The 10 best new restaurants in NYC right now'},{account:'eabornyc',reelUrl:'https://www.instagram.com/reel/C9EXAMPLE1/',views:850000,likes:32000,comments:410,engagement:3.8,date:'2026-07-12',caption:'This pasta spot in the West Village is unreal'},{account:'foodbabyny',reelUrl:'https://www.instagram.com/reel/C9EXAMPLE2/',views:720000,likes:28000,comments:350,engagement:3.9,date:'2026-07-10',caption:'POV: You found the best brunch in Brooklyn'},{account:'devourpower',reelUrl:'https://www.instagram.com/reel/C9EXAMPLE3/',views:950000,likes:38000,comments:520,engagement:4.1,date:'2026-07-08',caption:'This steak is cooked PERFECTLY'},{account:'nycfoodie',reelUrl:'https://www.instagram.com/reel/C9EXAMPLE4/',views:680000,likes:25000,comments:310,engagement:3.7,date:'2026-07-05',caption:'Best cocktails in the city'}],hotels:[{account:'thehotelwashington',reelUrl:'https://www.instagram.com/reel/C9HEXAMPLE1/',views:420000,likes:18000,comments:230,engagement:4.3,date:'2026-07-14',caption:'Rooftop views that hit different at golden hour'},{account:'fshotels',reelUrl:'https://www.instagram.com/reel/C9HEXAMPLE2/',views:680000,likes:25000,comments:180,engagement:3.7,date:'2026-07-11',caption:'Suite life at its finest'},{account:'rosewoodhotels',reelUrl:'https://www.instagram.com/reel/C9HEXAMPLE3/',views:530000,likes:22000,comments:290,engagement:4.2,date:'2026-07-09',caption:'When the lobby is this beautiful'},{account:'pendryhotels',reelUrl:'https://www.instagram.com/reel/C9HEXAMPLE4/',views:390000,likes:15000,comments:170,engagement:3.9,date:'2026-07-06',caption:'Pool day vibes at Pendry'},{account:'thedorseydc',reelUrl:'https://www.instagram.com/reel/C9HEXAMPLE5/',views:310000,likes:12000,comments:140,engagement:3.9,date:'2026-07-03',caption:'The cocktail bar at The Dorsey'}]};
var currentCategory='restaurants',selectedReels=new Set(),docUrl='';
function setCategory(cat){currentCategory=cat;document.querySelectorAll('.toggle button').forEach(function(b){b.classList.toggle('active',b.dataset.cat===cat);});if(document.getElementById('results').classList.contains('show'))renderResults();}
function initiate(){var btn=document.getElementById('initiateBtn');btn.disabled=true;selectedReels.clear();updateSelBar();var overlay=document.getElementById('juiceboxOverlay'),juice=document.getElementById('jbJuice'),progress=document.getElementById('jbProgress');overlay.classList.add('active');juice.style.transition='none';juice.style.height='100%';juice.classList.remove('draining');createBubbles();var messages=['Finding the freshest reels','Analyzing engagement rates','Filtering top performers','Ranking by virality','Almost done...'];setTimeout(function(){juice.style.transition='height 6s ease-in-out';juice.classList.add('draining');},200);var msgIdx=0;var msgInterval=setInterval(function(){msgIdx++;if(msgIdx<messages.length)progress.textContent=messages[msgIdx];},1200);setTimeout(function(){clearInterval(msgInterval);overlay.classList.remove('active');juice.classList.remove('draining');btn.disabled=false;renderResults();document.getElementById('results').classList.add('show');document.getElementById('results').scrollIntoView({behavior:'smooth'});},6500);}
function createBubbles(){var c=document.getElementById('jbBubbles');c.innerHTML='';for(var i=0;i<12;i++){var b=document.createElement('div');b.className='jb-bubble';b.style.left=Math.random()*90+'%';b.style.bottom=Math.random()*40+'%';b.style.animationDelay=Math.random()*3+'s';b.style.animationDuration=(1+Math.random()*2)+'s';b.style.width=(4+Math.random()*8)+'px';b.style.height=b.style.width;c.appendChild(b);}}
function renderResults(){var data=LOCAL_DATA[currentCategory],grid=document.getElementById('grid'),title=document.getElementById('resultsTitle'),count=document.getElementById('resultsCount');title.textContent=currentCategory==='restaurants'?'Top Restaurant Reels':'Top Hotel Reels';count.textContent=data.length+' results';grid.innerHTML=data.map(function(item,i){var ini=item.account.slice(0,2).toUpperCase(),embedUrl=item.reelUrl+'embed/',dlUrl='https://djack-netizen.github.io/personal-bot/dl.html?url='+encodeURIComponent(item.reelUrl),isSel=selectedReels.has(currentCategory+':'+i);return '<div class="card'+(isSel?' selected':'')+'" data-idx="'+i+'"><div class="card-check"><input type="checkbox" '+(isSel?'checked':'')+' onchange="toggleSelect(\''+currentCategory+'\','+i+',this.checked)"></div><div class="card-top"><div class="avatar">'+ini+'</div><span class="username">@'+item.account+'</span></div><iframe class="card-embed" src="'+embedUrl+'" loading="lazy" allowfullscreen allow="encrypted-media"></iframe><div class="card-stats"><div class="stat"><div class="stat-val">'+formatNum(item.views)+'</div><div class="stat-label">Views</div></div><div class="stat"><div class="stat-val">'+formatNum(item.likes)+'</div><div class="stat-label">Likes</div></div><div class="stat"><div class="stat-val">'+formatNum(item.comments)+'</div><div class="stat-label">Comments</div></div><div class="stat"><div class="stat-val">'+item.engagement+'%</div><div class="stat-label">Eng.</div></div></div><div class="card-footer"><span class="card-date">'+formatDate(item.date)+'</span><a class="card-dl" href="'+dlUrl+'" target="_blank">\u2B07 Download</a></div></div>';}).join('');}
function toggleSelect(cat,idx,checked){var key=cat+':'+idx;if(checked)selectedReels.add(key);else selectedReels.delete(key);document.querySelectorAll('.card').forEach(function(c){var ci=parseInt(c.dataset.idx),ck=currentCategory+':'+ci;c.classList.toggle('selected',selectedReels.has(ck));});updateSelBar();}
function clearSelection(){selectedReels.clear();document.querySelectorAll('.card').forEach(function(c){c.classList.remove('selected');});document.querySelectorAll('.card-check input').forEach(function(cb){cb.checked=false;});updateSelBar();}
function updateSelBar(){var bar=document.getElementById('selBar'),count=document.getElementById('selCount'),n=selectedReels.size;bar.classList.toggle('show',n>0);count.textContent=n+' reel'+(n!==1?'s':'')+' selected';}
function openPlanModal(){document.getElementById('planModal').classList.add('active');document.getElementById('planForm').style.display='block';document.getElementById('planLoading').style.display='none';document.getElementById('planResult').style.display='none';}
function closePlanModal(){document.getElementById('planModal').classList.remove('active');}
function generateShotList(){var client=document.getElementById('clientSelect').value;if(!client){alert('Please select a client');return;}var shootDate=document.getElementById('shootDate').value,shootStart=document.getElementById('shootStart').value,shootEnd=document.getElementById('shootEnd').value,shotTypes=[].slice.call(document.querySelectorAll('.checkbox-group input:checked')).map(function(cb){return cb.value;});var reels=[];selectedReels.forEach(function(key){var parts=key.split(':');reels.push(LOCAL_DATA[parts[0]][parseInt(parts[1])]);});document.getElementById('planForm').style.display='none';document.getElementById('planLoading').style.display='block';var payload={client:client,shootDate:shootDate,shootStart:shootStart,shootEnd:shootEnd,shotTypes:shotTypes,reels:reels};fetch('https://script.google.com/a/macros/openventures.io/s/PLACEHOLDER/exec',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json();}).then(function(data){docUrl=data.docUrl||'https://docs.google.com/document/d/PLACEHOLDER';showShotResult();}).catch(function(){docUrl='https://docs.google.com/document/d/PLACEHOLDER';setTimeout(showShotResult,2000);});}
function showShotResult(){document.getElementById('planLoading').style.display='none';document.getElementById('planResult').style.display='block';document.getElementById('docLink').href=docUrl;}
function copyDocLink(){navigator.clipboard.writeText(docUrl).then(function(){var btn=event.target;btn.textContent='Copied!';setTimeout(function(){btn.textContent='Copy Link';},2000);});}
function emailDoc(){var subject=encodeURIComponent('Shot List - OPN Agency'),body=encodeURIComponent('Here is the shot list: '+docUrl);window.open('mailto:?subject='+subject+'&body='+body);}
document.getElementById('planModal').addEventListener('click',function(e){if(e.target===document.getElementById('planModal'))closePlanModal();});
function formatNum(n){if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return n.toString();}
function formatDate(d){var dt=new Date(d+'T00:00:00');return dt.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
